- name: Create memcached_exporter group
  group:
    name: '{{ memcached_exporter_group }}'

- name: Create memcached_exporter user
  user:
    name: '{{ memcached_exporter_user }}'
    group: '{{ memcached_exporter_group }}'
    createhome: false
    shell: '/usr/sbin/nologin'

- name: Download memcached_exporter tarball
  get_url:
    url: '{{ memcached_exporter_url }}'
    dest: '/tmp/{{ memcached_exporter_release_name }}.tar.gz'
    checksum: 'sha256:{{ memcached_exporter_checksum }}'
    mode: 0644

- name: Unpack tarball
  unarchive:
    src: '/tmp/{{ memcached_exporter_release_name }}.tar.gz'
    dest: '/tmp'
    creates: '/tmp/{{ memcached_exporter_release_name }}/memcached_exporter'
    remote_src: true

- name: Copy binary
  copy:
    src: '/tmp/{{ memcached_exporter_release_name }}/memcached_exporter'
    dest: '/usr/local/bin/memcached_exporter'
    remote_src: true
    mode: 0755
  notify: restart memcached_exporter

- name: Copy the memcached_exporter systemd service file
  template:
    src: 'memcached_exporter.service.j2'
    dest: '/lib/systemd/system/memcached_exporter.service'
    owner: '{{ memcached_exporter_user }}'
    group: '{{ memcached_exporter_group }}'
    mode: 0644
  notify: restart memcached_exporter
